---
- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/ysql_num_shards_per_tserver?
  value: ((ysql_num_shards_per_tserver))

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/ysql_num_shards_per_tserver?
  value: ((ysql_num_shards_per_tserver))
