# https://github.com/crazy-max/ghaction-github-labeler
---
- name: area/docs
  color: 0075ca
  description: improvements or additions to documentation

- name: area/ycql
  color: 495fc1
  description: things involving YCQL API

- name: area/yedis
  color: 495fc1
  description: things involving YEDIS API

- name: area/ysql
  color: 495fc1
  description: things involving YSQL API

- name: deployment-mgmt
  color: a59ae0
  description: changes involving ci-cd, builds, release, deployment manifests, operator files, etc.

- name: feedback/upstream-yb
  color: b3b6fc
  description: something probably best handled in upstream yugabyte

- name: feedback/yugabyte-boshrelease
  color: b3b6fc
  description: general feedback for this project

- name: good-enough-for-now
  color: cfd3d7
  description: it's not done, it just... well, it's good enough I guess

- name: job/yb-master
  color: 1c778c
  description: code changes affecting yb-master job

- name: job/yb-tserver
  color: 1c778c
  description: code changes affecting yb-tserver job

- name: kind/bug
  color: f1b0f2
  description: something isn't working

- name: kind/enhancement
  color: f1b0f2
  description: an enhancement of an existing feature

- name: kind/new-feature
  color: f1b0f2
  description: request for a completely new feature

- name: kind/question
  color: f1b0f2
  description: this is a general use question, etc.

- name: priority/just-a-thought
  color: f9e25e
  description: what's lower than low? ice-low

- name: priority/low
  color: f9e25e
  description: low priority

- name: priority/medium
  color: f9e25e
  description: medium priority

- name: priority/high
  color: f9e25e
  description: highest priority

- name: status/parking-lot
  color: efc092
  description: on hold or soon to be abandonded

- name: status/probably-vaporware
  color: efc092
  description: just goofing around with something or other

- name: wontfix
  color: cfd3d7
  description: this will not be worked on
