---
common_gflags:
  enable_ysql: false # TODO should be true or not even here
  max_log_size: 256
  minloglevel: 0
  placement_cloud: aws
  placement_region: us-west-2
  stop_logging_if_full_disk: true
