---
tags: {}

name: yugabyte

releases:
  - name: yugabyte
    version: latest
  - name: bpm
    version: latest

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-20000
  update_watch_time: 10000-20000

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: master
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: 1
    vm_type: m5.large
    persistent_disk_type: "30720"
    stemcell: default
    networks: [name: services-network]
    jobs:
      - name: yb-master
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        provides: { yb-master: { as: yb-master-provider } }
        properties:
          gflags: ((master_gflags))

  - name: tserver
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: 3
    vm_type: m5.large
    persistent_disk_type: "30720"
    stemcell: default
    networks: [name: services-network]
    jobs:
      - name: yb-tserver
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        provides: { yb-tserver: { as: yb-tserver-provider } }
        properties:
          gflags: ((tserver_gflags))
          server_broadcast_addresses_port: 9101
          rpc_bind_addresses_port: 9101

  - name: yb-sample-apps
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: 0
    vm_type: t3.micro
    persistent_disk_type: "30720"
    stemcell: default
    networks: [name: services-network]
    jobs:
      - name: yb-sample-apps
        release: yugabyte
        consumes:
          yb-master: { from: yb-master-provider }
          yb-tserver: { from: yb-tserver-provider }

variables: []
