---
tags: {}

name: ((deployment_name))

releases:
  - name: yugabyte
    version: latest
  - name: bpm
    version: latest

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-20000
  update_watch_time: 10000-20000

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: master
    azs: [z1]
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: yb-master
        release: yugabyte
        provides:
          yb-master: { as: yb-master-provider }
        consumes:
          yb-master: { from: yb-master-provider }

  - name: tserver
    azs: [z1]
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: yb-tserver
        release: yugabyte
        consumes:
          yb-master: { from: yb-master-provider }

variables: []
