---
- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/post_start_delay?
  value: ((master_post_start_delay))

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/post_start_delay?
  value: ((tserver_post_start_delay))
