---
- type: replace
  path: /instance_groups/-
  value:
    name: sample-rediskeyvalue
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: 1
    vm_type: t3.small
    persistent_disk_type: "1024"
    stemcell: xenial
    networks: [name: ((network_name))]
    jobs:
      - name: yb-sample-apps
        release: yugabyte
        consumes: { yb-tserver: { from: yb-tserver-provider } }
        properties:
          tserver_port_target: 6379
          workload:
            type: RedisKeyValue
            args:
              num_unique_keys: 1000000000
              num_reads: -1
              num_writes: -1
              num_threads_read: 2
              num_threads_write: 2
