---
version: "2"

env:
  YB_VERSION: 2.0.11.0

tasks:
  git:
    cmds:
      - git add -A
      - git commit -m "autocommit"

  dl-blobs:
    status:
      - test -f /tmp/yugabyte-${YB_VERSION}-linux.tar.gz
    cmds:
      - curl -o /tmp/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  add-blobs:
    cmds:
      - task: dl-blobs
      - bosh add-blob /tmp/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz

  deploy-production:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/production/yugabyte.yml \
          -o manifests/production/operators/geo-distribution-flags.yml \
          -o manifests/production/operators/gflags.yml \
          -o manifests/production/operators/scaling.yml \
          -o manifests/production/operators/update-strategy.yml \
          -l manifests/production/vars.yml \
          --no-redact \
          --non-interactive

  deploy-yb-ctl:
    cmds:
      - |
        bosh -d yb-ctl deploy manifests/yb-ctl/yb-ctl.yml \
          -l manifests/yb-ctl/vars.yml \
          --no-redact \
          --non-interactive

  deploy-yugabyted:
    cmds:
      - |
        bosh -d yb-ctl deploy manifests/yugabyted/yugabyted.yml \
          -l manifests/yugabyted/vars.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      - task: add-blobs
      - bosh create-release --force
      - bosh upload-release
      - task: deploy-yugabyted
