---
version: "2"

env:
  OPENJDK_VERSION: 1.8.0_242
  PYTHON_VERSION: 3.8.1
  YB_SAMPLE_APPS_VERSION: 1.2.1
  YB_VERSION: 2.0.11.0

tasks:
  dl-openjdk:
    status: ["test -f /tmp/openjdk-${OPENJDK_VERSION}.tar.gz"]
    cmds:
      - curl -o /tmp/openjdk-${OPENJDK_VERSION}.tar.gz -L "https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-${OPENJDK_VERSION}-bionic.tar.gz"

  dl-python:
    status:
      - "test -f /tmp/Python-${PYTHON_VERSION}.tgz"
      - "test -f /tmp/pip-20.0.2.tar.gz"
      - "test -f /tmp/setuptools-45.2.0.zip"
    cmds:
      - curl -o /tmp/Python-${PYTHON_VERSION}.tgz -L "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz"
      - curl -o /tmp/pip-20.0.2.tar.gz -L "https://files.pythonhosted.org/packages/8e/76/66066b7bc71817238924c7e4b448abdb17eb0c92d645769c223f9ace478f/pip-20.0.2.tar.gz"
      - curl -o /tmp/setuptools-45.2.0.zip -L "https://files.pythonhosted.org/packages/68/75/d1d7b7340b9eb6e0388bf95729e63c410b381eb71fe8875cdfd949d8f9ce/setuptools-45.2.0.zip"

  dl-yb-sample-apps:
    status: ["test -f /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar"]
    cmds:
      - wget -O /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar https://github.com/yugabyte/yb-sample-apps/releases/download/${YB_SAMPLE_APPS_VERSION}/yb-sample-apps.jar

  dl-yb:
    status: ["test -f /tmp/yugabyte-${YB_VERSION}-linux.tar.gz"]
    cmds:
      - curl -o /tmp/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  add-blobs:
    cmds:
      - task: dl-openjdk
      - bosh add-blob /tmp/openjdk-${OPENJDK_VERSION}.tar.gz openjdk/openjdk-${OPENJDK_VERSION}.tar.gz
      - task: dl-python
      - bosh add-blob /tmp/Python-${PYTHON_VERSION}.tgz python/Python-${PYTHON_VERSION}.tgz
      - bosh add-blob /tmp/pip-20.0.2.tar.gz python/pip-20.0.2.tar.gz
      - bosh add-blob /tmp/setuptools-45.2.0.zip python/setuptools-45.2.0.zip
      - task: dl-yb-sample-apps
      - bosh add-blob /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar yugabyte/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar
      - task: dl-yb
      - bosh add-blob /tmp/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz

  deploy:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/yugabyte.yml \
          -o manifests/operators/release-create-from-local.yml \
          -l manifests/vars.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      - task: add-blobs
      - task: deploy
