---
version: "2"

env:
  OPENJDK_VERSION: 1.8.0_242
  PYTHON_PIP_URL: "https://files.pythonhosted.org/packages/ed/94/391a003107f6ec997c314199d03bff1c105af758ee490e3255353574487b/pip-1.5.2.tar.gz"
  PYTHON_PIP_VERSION: 1.5.2
  PYTHON_SETUPTOOLS_URL: "https://files.pythonhosted.org/packages/72/16/738ef65b2659b3a84573c51094afbfb0c263f7cd51911c3caf5e4f7b8c0b/setuptools-2.2.zip"
  PYTHON_SETUPTOOLS_VERSION: 2.2
  PYTHON_VERSION: 2.7.6
  YB_SAMPLE_APPS_VERSION: 1.2.1
  YB_VERSION: 2.1.0.0

tasks:
  dl-openjdk:
    status: ["test -f /tmp/yugablob/openjdk-${OPENJDK_VERSION}.tar.gz"]
    cmds:
      - curl -o /tmp/yugablob/openjdk-${OPENJDK_VERSION}.tar.gz -L "https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-${OPENJDK_VERSION}-bionic.tar.gz"

  dl-python:
    status:
      - "test -f /tmp/yugablob/Python-${PYTHON_VERSION}.tgz"
      - "test -f /tmp/yugablob/pip-${PYTHON_PIP_VERSION}.tar.gz"
      - "test -f /tmp/yugablob/setuptools-${PYTHON_SETUPTOOLS_VERSION}.zip"
    cmds:
      - curl -o /tmp/yugablob/pip-${PYTHON_PIP_VERSION}.tar.gz -L "${PYTHON_PIP_URL}"
      - curl -o /tmp/yugablob/Python-${PYTHON_VERSION}.tgz -L "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz"
      - curl -o /tmp/yugablob/setuptools-${PYTHON_SETUPTOOLS_VERSION}.zip -L "${PYTHON_SETUPTOOLS_URL}"

  dl-yb-sample-apps:
    status:
      ["test -f /tmp/yugablob/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar"]
    cmds:
      - wget -O /tmp/yugablob/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar https://github.com/yugabyte/yb-sample-apps/releases/download/${YB_SAMPLE_APPS_VERSION}/yb-sample-apps.jar

  dl-yb:
    status: ["test -f /tmp/yugablob/yugabyte-${YB_VERSION}-linux.tar.gz"]
    cmds:
      - curl -o /tmp/yugablob/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  add-blobs:
    cmds:
      - mkdir -p /tmp/yugablob
      - task: dl-openjdk
      - bosh add-blob /tmp/yugablob/openjdk-${OPENJDK_VERSION}.tar.gz openjdk/openjdk-${OPENJDK_VERSION}.tar.gz
      - task: dl-python
      - bosh add-blob /tmp/yugablob/Python-${PYTHON_VERSION}.tgz python/Python-${PYTHON_VERSION}.tgz
      - bosh add-blob /tmp/yugablob/pip-${PYTHON_PIP_VERSION}.tar.gz python/pip-${PYTHON_PIP_VERSION}.tar.gz
      - bosh add-blob /tmp/yugablob/setuptools-${PYTHON_SETUPTOOLS_VERSION}.zip python/setuptools-${PYTHON_SETUPTOOLS_VERSION}.zip
      - task: dl-yb-sample-apps
      - bosh add-blob /tmp/yugablob/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar yugabyte/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar
      - task: dl-yb
      - bosh add-blob /tmp/yugablob/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz

  run-errand:
    cmds:
      - bosh -d yugabyte run-errand setup_redis_table

  deploy:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/yugabyte.yml \
          -o manifests/operators/create-release-from-local.yml \
          -o manifests/operators/enable-sample-apps.yml \
          -o manifests/operators/enable-syslog-forwarder.yml \
          -o manifests/operators/gflags.yml \
          -o manifests/operators/tserver-rpc-bind-port.yml \
          -l manifests/vars.yml \
          -l manifests/versions.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      # - task: add-blobs
      - task: deploy
      # - task: run-errand
