---
version: "2"

tasks:
  git:
    cmds:
      - git add -A
      - git commit -m "autocommit"

  dl-blobs:
    status:
      - test -f /tmp/yugabyte-2.0.11.0-linux.tar.gz
    cmds:
      - curl -o /tmp/yugabyte-2.0.11.0-linux.tar.gz https://downloads.yugabyte.com/yugabyte-2.0.11.0-linux.tar.gz

  add-blobs:
    cmds:
      - task: dl-blobs
      - bosh add-blob /tmp/yugabyte-2.0.11.0-linux.tar.gz yugabyte/yugabyte-2.0.11.0-linux.tar.gz

  deploy:
    cmds:
      - bosh -d yugabyte deploy manifests/yugabyte.yml -o manifests/operators/scaling.yml -l manifests/vars.yml --non-interactive

  test:
    cmds:
      - task: add-blobs
      - bosh create-release --force
      - bosh upload-release
      - task: deploy
