---
version: "2"

tasks:
  git:
    cmds:
      - git add -A
      - git commit -m "autocommit"

  dev-release:
    cmds:
      - bosh create-release --force

  dl-yb:
    dir: scratchpad
    cmds:
      - wget https://downloads.yugabyte.com/yugabyte-2.0.11.0-linux.tar.gz
      # - curl https://downloads.yugabyte.com/yugabyte-2.0.11.0-linux.tar.gz | tar xz -C src -
      # - tar xvfz yugabyte-2.0.11.0-linux.tar.gz && cd yugabyte-2.0.11.0/

  generate-package:
    cmds:
      - bosh generate-package
