---
version: "2"

env:
  YB_SAMPLE_APPS_VERSION: 1.2.1
  YB_VERSION: 2.0.11.0
  OPENJDK_VERSION: 1.8.0_242

tasks:
  dl-openjdk:
    status: ["test -f /tmp/openjdk-${OPENJDK_VERSION}.tar.gz"]
    cmds:
      - curl -o /tmp/openjdk-${OPENJDK_VERSION}.tar.gz -L "https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/openjdk-jre-${OPENJDK_VERSION}-bionic.tar.gz"

  dl-yb-sample-apps:
    status: ["test -f /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar"]
    cmds:
      - wget -O /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar https://github.com/yugabyte/yb-sample-apps/releases/download/${YB_SAMPLE_APPS_VERSION}/yb-sample-apps.jar

  dl-yb:
    status: ["test -f /tmp/yugabyte-${YB_VERSION}-linux.tar.gz"]
    cmds:
      - curl -o /tmp/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  add-blobs:
    cmds:
      - task: dl-yb
      - bosh add-blob /tmp/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz
      - task: dl-openjdk
      - bosh add-blob /tmp/openjdk-${OPENJDK_VERSION}.tar.gz openjdk/openjdk-${OPENJDK_VERSION}.tar.gz
      - task: dl-yb-sample-apps
      - bosh add-blob /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar yugabyte/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar

  deploy:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/yugabyte.yml \
          -o manifests/operators/release-create-from-local.yml \
          -l manifests/vars.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      - task: add-blobs
      - task: deploy
