---
version: "2"

env:
  YB_VERSION: 2.0.11.0

tasks:
  git:
    cmds:
      - git add -A
      - git commit -m "autocommit"

  dl-blobs:
    status:
      - test -f /tmp/yugabyte-${YB_VERSION}-linux.tar.gz
    cmds:
      - curl -o /tmp/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  add-blobs:
    cmds:
      - task: dl-blobs
      - bosh add-blob /tmp/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz

  deploy:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/yugabyte.yml \
          -o manifests/operators/geo-distribution-flags.yml \
          -o manifests/operators/optional-ysql.yml \
          -o manifests/operators/override-host-bindings.yml \
          -o manifests/operators/scaling.yml \
          -o manifests/operators/syslog-forwarder.yml \
          -l manifests/vars.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      - task: add-blobs
      - bosh create-release --force
      - bosh upload-release
      - task: deploy
