---
version: "3"

env:
  OPENJDK_VERSION: 1.8.0_265
  PYTHON_VERSION: 2.7.6
  YB_SAMPLE_APPS_VERSION: 1.2.1
  YB_VERSION: 2.2.2.0

tasks:
  dl-openjdk:
    status: ["test -f /tmp/yugablob/openjdk-${OPENJDK_VERSION}.tar.gz"]
    cmds:
      - |
        curl -o /tmp/yugablob/jdk-index.yml https://java-buildpack.cloudfoundry.org/openjdk/bionic/x86_64/index.yml
        OPENJDK_URL=$(grep -o "${OPENJDK_VERSION}: [^, }]*" /tmp/yugablob/jdk-index.yml | sed 's/^.*: //')
        curl -o /tmp/yugablob/openjdk-${OPENJDK_VERSION}.tar.gz -L "${OPENJDK_URL}"

  dl-python:
    status:
      - "test -f /tmp/yugablob/Python-${PYTHON_VERSION}.tgz"
    cmds:
      - curl -o /tmp/yugablob/Python-${PYTHON_VERSION}.tgz -L "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz"

  dl-yb-sample-apps:
    status:
      ["test -f /tmp/yugablob/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar"]
    cmds:
      - wget -O /tmp/yugablob/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar https://github.com/yugabyte/yb-sample-apps/releases/download/${YB_SAMPLE_APPS_VERSION}/yb-sample-apps.jar

  dl-yb:
    status: ["test -f /tmp/yugablob/yugabyte-${YB_VERSION}-linux.tar.gz"]
    cmds:
      - curl -o /tmp/yugablob/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  clean-blob-tmp-dir:
    cmds:
      - rm -rf /tmp/yugablob

  add-blobs:
    cmds:
      - echo "" >config/blobs.yml # resets the blobs file to purge any old blob definitions
      - mkdir -p /tmp/yugablob
      - task: dl-openjdk
      - bosh add-blob /tmp/yugablob/openjdk-${OPENJDK_VERSION}.tar.gz openjdk/openjdk-${OPENJDK_VERSION}.tar.gz
      - task: dl-python
      - bosh add-blob /tmp/yugablob/Python-${PYTHON_VERSION}.tgz python/Python-${PYTHON_VERSION}.tgz
      - task: dl-yb-sample-apps
      - bosh add-blob /tmp/yugablob/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar yugabyte/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar
      - task: dl-yb
      - bosh add-blob /tmp/yugablob/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz

  run-errand:
    cmds:
      - bosh -d yugabyte run-errand setup_redis_table

  deploy:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/yugabyte.yml \
          -o manifests/operators/development/create-release-from-local.yml \
          -o manifests/operators/gflags.yml \
          -o manifests/operators/logging/stderrthreshold.yml \
          -o manifests/operators/placement-options.yml \
          -o manifests/operators/sample-apps/cassandrakeyvalue.yml \
          -o manifests/operators/sample-apps/sqlinserts.yml \
          -l manifests/operators/sample-apps/vars.yml \
          -l manifests/vars.yml \
          -l manifests/versions.yml \
          -l manifests/operators/development/vars.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      # - task: add-blobs
      - task: deploy
      # - task: run-errand
