---
version: "2"

env:
  YB_SAMPLE_APPS_VERSION: 1.2.1
  YB_VERSION: 2.0.11.0
  OPENJDK_JAVA_VERSION: x

tasks:
  git:
    cmds:
      - git add -A
      - git commit -m "autocommit"

  dl-openjdk:
    status:
      - test -f /tmp/openjdk_1.8.0
    cmds:
      - openjdk_1.8.0
      - curl -o /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar https://api.adoptopenjdk.net/v2/binary/releases/openjdk${OPENJDK_JAVA_VERSION}?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jre"

  dl-yb-sample-apps:
    status:
      - test -f /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar
    cmds:
      - curl -o /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar https://github.com/yugabyte/yb-sample-apps/releases/download/v${YB_SAMPLE_APPS_VERSION}/yb-sample-apps.jar?raw=true

  dl-yb:
    status:
      - test -f /tmp/yugabyte-${YB_VERSION}-linux.tar.gz
    cmds:
      - curl -o /tmp/yugabyte-${YB_VERSION}-linux.tar.gz https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz

  add-blobs:
    cmds:
      - task: dl-yb
      - bosh add-blob /tmp/yugabyte-${YB_VERSION}-linux.tar.gz yugabyte/yugabyte-${YB_VERSION}-linux.tar.gz
      - task: dl-yb-sample-apps
      - bosh add-blob /tmp/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar yugabyte/yb-sample-apps-${YB_SAMPLE_APPS_VERSION}.jar

  deploy-production:
    cmds:
      - |
        bosh -d yugabyte deploy manifests/production/yugabyte.yml \
          -o manifests/production/operators/gflags.yml \
          -o manifests/production/operators/scaling.yml \
          -o manifests/production/operators/update-strategy.yml \
          -l manifests/production/vars.yml \
          --no-redact \
          --non-interactive

  deploy-yugabyted:
    # note: if it starts acting up, use --skip-drain=yugabyted
    cmds:
      - |
        bosh -d yugabyted deploy manifests/yugabyted/yugabyted.yml \
          -l manifests/yugabyted/vars.yml \
          --no-redact \
          --non-interactive

  deploy-yb-ctl:
    cmds:
      - |
        bosh -d yb-ctl deploy manifests/yb-ctl/yb-ctl.yml \
          -l manifests/yb-ctl/vars.yml \
          --no-redact \
          --non-interactive

  test:
    cmds:
      - task: add-blobs
      - bosh create-release --force
      - bosh upload-release
      - task: deploy-production
