---
tags: {}

name: ((deployment_name))

releases:
  - name: yugabyte
    version: latest
  - name: bpm
    version: latest

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-20000
  update_watch_time: 10000-20000

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: yugabyted
    azs: ((yugabyted_azs))
    instances: 1
    vm_type: ((yugabyted_vm_type))
    persistent_disk_type: ((yugabyted_persistent_disk_type))
    stemcell: default
    networks:
      - name: ((yugabyted_network))
    jobs:
      - name: yugabyted
        release: yugabyte

variables: []
