---
processes:
  - name: yb-master
    executable: /var/vcap/packages/yugabyte/bin/yb-master
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-master/config/master.conf
    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    env:
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      PATH: /var/vcap/packages/yugabyte:/var/vcap/packages/yugabyte/postgres:/var/vcap/packages/yugabyte/postgres/bin:/home/vcap/bin:/home/vcap/.local/bin:/var/vcap/jobs/bpm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/var/vcap/bosh/bin
