---
processes:
  - name: yb-master
    workdir: /var/vcap/data/packages/yugabyte/2a0089f71899ee62de9d4b69e69af783745c0881
    executable: bin/yb-master
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-master/config/master.conf
    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    env:
      YB_PG_FALLBACK_SYSTEM_USER_NAME: vcap
    # capabilities:
    #   - SETUID
    #   - SYS_ADMIN
    unsafe:
      privileged: false
