---
processes:
  - name: yb-master
    workdir: /var/vcap/data/packages/yugabyte/db77bbcc0b1b255adcfdda76698a1a7051e6b43b
    executable: bin/yb-master
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-master/config/master.conf
      # - --initial_sys_catalog_snapshot_dest_path=/var/vcap/store/yb-master
      - --initial_sys_catalog_snapshot_path=/var/vcap/store/yb-master
    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    env:
      YB_PG_FALLBACK_SYSTEM_USER_NAME: vcap
      # YB_CTEST_VERBOSE: '1'
    # capabilities:
    #   - SETUID
    #   - SYS_ADMIN
    unsafe:
      privileged: false
