---
processes:
  - name: yb-master
    workdir: /var/vcap/data/packages/yugabyte/db77bbcc0b1b255adcfdda76698a1a7051e6b43b
    executable: bin/yb-master
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-master/config/master.conf
      - --use_initial_sys_catalog_snapshot=false # https://github.com/yugabyte/yugabyte-db/commit/c3a62bb1d60864254f832d489d976bdd7c422145
    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    env:
      YB_PG_FALLBACK_SYSTEM_USER_NAME: vcap
    unsafe:
      privileged: false
