---
common_gflags:
  default_memory_limit_to_ram_ratio: 0.85
  enable_ysql: false # TODO should be true or not even here
  max_log_size: 256
  minloglevel: 0
  placement_cloud: aws
  placement_region: us-west-2
  start_pgsql_proxy: false # TODO probably can be removed if enable ysql is false too
  stop_logging_if_full_disk: true
  use_cassandra_authentication: false # TODO this is a valid flag for tserver but not for masters, but since we're passing as flagfile, it doesn't fail validation... which is a blessing and a curse, really
master_instances: 3
tserver_instances: 3
sample_cassandrakeyvalue_instances: 1 # can't have test apps running against cluster until https://github.com/yugabyte/yb-sample-apps/pull/2 supports auth
sample_rediskeyvalue_instances: 1
