---
deployment_name: yugabyte
network: services-network

setup_redis_table_errand_azs: [us-west-2a, us-west-2b, us-west-2c]
setup_redis_table_errand_persistent_disk_type: "1024"
setup_redis_table_errand_vm_type: t3.micro

syslog_address: q-s0.docker.services-network.splunk.bosh
syslog_port: 5514
syslog_tls_enabled: false

master_azs: [us-west-2a, us-west-2b, us-west-2c]
master_instances: 1
master_persistent_disk_type: "10240"
master_vm_type: t3.micro
master_gflags:
  default_memory_limit_to_ram_ratio: 0.85
  # enable_ysql: false
  placement_cloud: aws
  placement_region: us-west-2

tserver_azs: [us-west-2a, us-west-2b, us-west-2c]
tserver_instances: 1
tserver_persistent_disk_type: "30720"
tserver_rpc_bind_port: 9101
tserver_vm_type: m5.large
tserver_gflags:
  default_memory_limit_to_ram_ratio: 0.85
  # enable_ysql: false
  placement_cloud: aws
  placement_region: us-west-2
  use_cassandra_authentication: true
