---
master_azs: [us-west-2a, us-west-2b, us-west-2c]
master_enable_ysql: false
master_instances: 1
master_network: services-network
master_persistent_disk_type: "30720"
master_placement_cloud: aws
master_placement_region: us-west-2
master_rpc_bind_addresses: "0.0.0.0"
master_server_broadcast_addresses: "0.0.0.0"
master_vm_type: t3.micro
syslog_address: q-s0.docker.services-network.splunk.bosh
syslog_port: 5514
syslog_tls_enabled: false
tserver_azs: [us-west-2a, us-west-2b, us-west-2c]
tserver_enable_ysql: false
tserver_instances: 3
tserver_network: services-network
tserver_persistent_disk_type: "30720"
tserver_placement_cloud: aws
tserver_placement_region: us-west-2
tserver_rpc_bind_addresses: "0.0.0.0"
tserver_server_broadcast_addresses: "0.0.0.0"
tserver_vm_type: t3.small
