---
deployment_name: yugabyte
network: services-network

sample_cassandrakeyvalue_azs: [us-west-2a, us-west-2b, us-west-2c]
sample_cassandrakeyvalue_persistent_disk_type: "1024"
sample_cassandrakeyvalue_vm_type: t3.small
sample_rediskeyvalue_azs: [us-west-2a, us-west-2b, us-west-2c]
sample_rediskeyvalue_persistent_disk_type: "1024"
sample_rediskeyvalue_vm_type: t3.small

setup_redis_table_errand_azs: [us-west-2a, us-west-2b, us-west-2c]
setup_redis_table_errand_persistent_disk_type: "1024"
setup_redis_table_errand_vm_type: t3.micro

master_azs: [us-west-2a, us-west-2b, us-west-2c]
master_instances: 3
master_persistent_disk_type: "10240"
master_vm_type: t3.micro
master_gflags:
  default_memory_limit_to_ram_ratio: 0.85
  enable_ysql: false
  max_log_size: 256
  minloglevel: 0
  placement_cloud: aws
  placement_region: us-west-2
  stop_logging_if_full_disk: true

tserver_azs: [us-west-2a, us-west-2b, us-west-2c]
tserver_instances: 3
tserver_persistent_disk_type: "30720"
tserver_rpc_bind_port: 9101
tserver_vm_type: m5.large
tserver_gflags:
  default_memory_limit_to_ram_ratio: 0.85
  enable_ysql: false
  max_log_size: 256
  minloglevel: 0
  placement_cloud: aws
  placement_region: us-west-2
  stop_logging_if_full_disk: true
  use_cassandra_authentication: true
