---
master_instances: 1
master_persistent_disk_type: "30720"
master_vm_type: m5.large
master_azs: [us-west-2a]
master_network: services-network
tserver_azs: [us-west-2a]
tserver_instances: 1
tserver_network: services-network
tserver_persistent_disk_type: "30720"
tserver_vm_type: m5.large
