---
master_azs: [us-west-2a]
master_instances: 1
master_network: services-network
master_persistent_disk_type: "30720"
master_vm_type: m5.large
syslog_address: q-s0.docker.services-network.splunk.bosh
syslog_port: 5514
syslog_tls_enabled: false
tserver_azs: [us-west-2a]
tserver_instances: 1
tserver_network: services-network
tserver_persistent_disk_type: "30720"
tserver_vm_type: m5.large
