---
name: yugabyte

releases: []

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

instance_groups:
  - name: xyz
    azs:
      - z1
    instances: 1
    vm_type: c5.2xlarge
    persistent_disk_type: 250GB_gp2
    stemcell: default
    networks:
      - name: default
    jobs: []

variables: []

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: true
