---
tags: {}

name: yugabyte

releases:
  - name: yugabyte
    version: latest
  - name: bpm
    version: latest

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: master
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: ((master_instances))
    vm_type: t3.micro
    persistent_disk_type: "10240"
    stemcell: xenial
    networks: [name: services-network]
    jobs:
      - name: yb-master
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        provides: { yb-master: { as: yb-master-provider } }
        properties:
          gflags: ((common_gflags))

  - name: tserver
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: ((tserver_instances))
    vm_type: m5.large
    persistent_disk_type: "30720"
    stemcell: xenial
    networks: [name: services-network]
    jobs:
      - name: yb-tserver
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        provides: { yb-tserver: { as: yb-tserver-provider } }
        properties:
          gflags: ((common_gflags))
          server_broadcast_addresses_port: 9101
          rpc_bind_addresses_port: 9101
          ycql.databases.roles:
            - name: hank_hill
              password: propane_bwaaah

  - name: sample-cassandrakeyvalue
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: ((sample_cassandrakeyvalue_instances))
    vm_type: t3.small
    persistent_disk_type: "1024"
    stemcell: xenial
    networks: [name: services-network]
    jobs:
      - name: yb-sample-apps
        release: yugabyte
        consumes: { yb-tserver: { from: yb-tserver-provider } }
        properties:
          tserver_port_target: 9042
          workload:
            type: CassandraKeyValue
            args:
              num_unique_keys: 1000000000
              num_reads: -1
              num_writes: -1
              value_size: 256
              num_threads_read: 2
              num_threads_write: 2
              table_ttl_seconds: -1

  - name: sample-rediskeyvalue
    azs: [us-west-2a, us-west-2b, us-west-2c]
    instances: ((sample_rediskeyvalue_instances))
    vm_type: t3.small
    persistent_disk_type: "1024"
    stemcell: xenial
    networks: [name: services-network]
    jobs:
      - name: yb-sample-apps
        release: yugabyte
        consumes: { yb-tserver: { from: yb-tserver-provider } }
        properties:
          tserver_port_target: 6379
          workload:
            type: RedisKeyValue
            args:
              num_unique_keys: 1000000000
              num_reads: -1
              num_writes: -1
              num_threads_read: 2
              num_threads_write: 2

  - name: setup_redis_table
    azs: [us-west-2a, us-west-2b, us-west-2c]
    lifecycle: errand
    instances: 1
    vm_type: t3.micro
    persistent_disk_type: "1024"
    stemcell: xenial
    networks: [name: services-network]
    jobs:
      - name: yb-admin
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        properties:
          commands:
            - setup_redis_table

variables: []

stemcells:
  - alias: xenial
    os: ubuntu-xenial
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
