---
tags: {}

name: yugabyte

releases:
  - name: yugabyte
    version: latest
  - name: bpm
    version: latest

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: true

instance_groups:
  - name: master
    azs: [z1]
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: bpm
        release: bpm
      - name: yb-master
        release: yugabyte

  - name: tserver
    azs: [z1]
    instances: 1
    vm_type: default
    persistent_disk_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: bpm
        release: bpm
      - name: yb-tserver
        release: yugabyte

variables: []
