---
tags: {}

name: ((deployment_name))

releases:
  - name: yugabyte
    version: latest
  - name: bpm
    version: latest

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: master
    azs: ((master_azs))
    instances: ((master_instances))
    vm_type: ((master_vm_type))
    persistent_disk_type: ((master_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-master
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        provides: { yb-master: { as: yb-master-provider } }

  - name: tserver
    azs: ((tserver_azs))
    instances: ((tserver_instances))
    vm_type: ((tserver_vm_type))
    persistent_disk_type: ((tserver_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-tserver
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        provides: { yb-tserver: { as: yb-tserver-provider } }

  - name: setup_redis_table
    azs: ((setup_redis_table_errand_azs))
    lifecycle: errand
    instances: 1
    vm_type: ((setup_redis_table_errand_vm_type))
    persistent_disk_type: ((setup_redis_table_errand_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-admin
        release: yugabyte
        consumes: { yb-master: { from: yb-master-provider } }
        properties:
          commands: [setup_redis_table]

variables: []

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: 456.latest

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-200000
  update_watch_time: 1000-200000

features:
  randomize_az_placement: true
  use_dns_addresses: true
  use_short_dns_addresses: true
