---
tags: {}

name: ((deployment_name))

releases:
  - name: bpm
    version: ((bpm_version))
    sha1: ((bpm_sha1))
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=((bpm_version))
  - name: syslog
    version: ((syslog_release_version))
    url: https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=((syslog_release_version))
    sha1: ((syslog_release_sha1))
  - name: yugabyte
    version: ((yugabyte_boshrelease_version))
    url: https://github.com/aegershman/yugabyte-boshrelease/releases/download/((yugabyte_boshrelease_version))/yugabyte-((yugabyte_boshrelease_version)).tgz
    sha1: ((yugabyte_boshrelease_sha1))

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm
  - name: syslog_forwarder
    jobs:
      - name: syslog_forwarder
        release: syslog
        properties:
          syslog:
            address: ((syslog_address))
            port: ((syslog_port))
            transport: tcp
            tls_enabled: ((syslog_tls_enabled))
            filter_legacy_vcap_messages: true

            # audispd rule: remove audispd log event flooding if queue overflows
            # auditd rule: filter all logs to avoid "log file is larger than max size"
            custom_rule: |
              if ($programname contains "audispd") then stop
              if ($programname contains "auditd") then stop
          blackbox:
            log_filename: true

instance_groups:
  - name: master
    azs: ((master_azs))
    instances: ((master_instances))
    vm_type: ((master_vm_type))
    persistent_disk_type: ((master_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-master
        release: yugabyte
        properties:
          tls:
            node:
              ca: ((yugabyte-server-tls-master.ca))
              cert: ((yugabyte-server-tls-master.certificate))
              key: ((yugabyte-server-tls-master.private_key))
        custom_provider_definitions:
          - name: yb-master-address-link
            type: address

  - name: tserver
    azs: ((tserver_azs))
    instances: ((tserver_instances))
    vm_type: ((tserver_vm_type))
    persistent_disk_type: ((tserver_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-tserver
        release: yugabyte
        properties:
          ycql:
            cassandra_password: ((ycql_cassandra_password))
            databases:
              superusers:
                - name: admin
                  password: ((ycql_superuser_admin_password))
          ysql:
            databases:
              superusers:
                # TODO note: at least for the moment we're reusing the
                # same username/password in ysql as we are for ycql for convenience.
                # The reason we use ycql in the variable name is because... well, it came first.
                - name: admin
                  password: ((ycql_superuser_admin_password))
          tls:
            node:
              ca: ((yugabyte-server-tls-tserver.ca))
              cert: ((yugabyte-server-tls-tserver.certificate))
              key: ((yugabyte-server-tls-tserver.private_key))
        custom_provider_definitions:
          - name: yb-tserver-address-link
            type: address

  - name: setup_redis_table
    azs: ((setup_redis_table_errand_azs))
    lifecycle: errand
    instances: 1
    vm_type: ((setup_redis_table_errand_vm_type))
    persistent_disk_type: ((setup_redis_table_errand_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: setup_redis_table
        release: yugabyte
        properties:
          tls:
            node:
              ca: ((yugabyte-server-tls-master.ca))

variables:
  - name: ycql_cassandra_password
    type: password
    update_mode: converge
    options:
      length: 25

  - name: ycql_superuser_admin_password
    type: password
    update_mode: converge
    options:
      length: 25

  - name: yugabyte-server-tls-master
    type: certificate
    update_mode: converge
    options:
      ca: /services/tls_ca
      common_name: yugabyte
    consumes:
      alternative_name:
        from: yb-master-address-link
        properties: { wildcard: true }

  - name: yugabyte-server-tls-tserver
    type: certificate
    update_mode: converge
    options:
      ca: /services/tls_ca
      common_name: yugabyte
    consumes:
      alternative_name:
        from: yb-tserver-address-link
        properties: { wildcard: true }

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: 621.latest

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-200000
  update_watch_time: 1000-200000

features:
  randomize_az_placement: true
  use_dns_addresses: true
  use_short_dns_addresses: true
