---
tags: {}

name: ((deployment_name))

releases:
  - name: yugabyte
    version: ((yugabyte_boshrelease_version))
    url: https://github.com/aegershman/yugabyte-boshrelease/releases/download/((yugabyte_boshrelease_version))/yugabyte-((yugabyte_boshrelease_version)).tgz
    sha1: ((yugabyte_boshrelease_sha1))
  - name: bpm
    version: ((bpm_version))

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: master
    azs: ((master_azs))
    instances: ((master_instances))
    vm_type: ((master_vm_type))
    persistent_disk_type: ((master_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-master
        release: yugabyte
        properties:
          tls:
            node:
              ca: ((yugabyte-server-tls-master.ca))
              cert: ((yugabyte-server-tls-master.certificate))
              key: ((yugabyte-server-tls-master.private_key))
        custom_provider_definitions:
          - name: yb-master-address-link
            type: address

  - name: tserver
    azs: ((tserver_azs))
    instances: ((tserver_instances))
    vm_type: ((tserver_vm_type))
    persistent_disk_type: ((tserver_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: yb-tserver
        release: yugabyte
        properties:
          tls:
            node:
              ca: ((yugabyte-server-tls-tserver.ca))
              cert: ((yugabyte-server-tls-tserver.certificate))
              key: ((yugabyte-server-tls-tserver.private_key))
        custom_provider_definitions:
          - name: yb-tserver-address-link
            type: address

  - name: setup_redis_table
    azs: ((setup_redis_table_errand_azs))
    lifecycle: errand
    instances: 1
    vm_type: ((setup_redis_table_errand_vm_type))
    persistent_disk_type: ((setup_redis_table_errand_persistent_disk_type))
    stemcell: default
    networks: [name: ((network))]
    jobs:
      - name: setup_redis_table
        release: yugabyte
        properties:
          tls:
            enabled: ((use_node_to_node_encryption))
            node:
              ca: ((yugabyte-server-tls-master.ca))

variables:
  - name: yugabyte-server-tls-master
    type: certificate
    update_mode: converge
    options:
      ca: /services/tls_ca
      common_name: yugabyte-boshrelease-certificate
    consumes:
      alternative_name:
        from: yb-master-address-link
        properties: { wildcard: true }

  - name: yugabyte-server-tls-tserver
    type: certificate
    update_mode: converge
    options:
      ca: /services/tls_ca
      common_name: yugabyte-boshrelease-certificate
    consumes:
      alternative_name:
        from: yb-tserver-address-link
        properties: { wildcard: true }

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: 621.latest

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-200000
  update_watch_time: 1000-200000

features:
  randomize_az_placement: true
  use_dns_addresses: true
  use_short_dns_addresses: true
