---
name: yugabyte

instance_groups:
  - name: xyz
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs: []

variables: []

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: true

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases: []
