# very much subject to change, these vars are
# loaded last in testing tooling to be used
# for experimentation while developing this release
---
master_stderrthreshold: 1
syslog_address: q-s0.docker.services-network.splunk.bosh
syslog_port: 5514
syslog_tls_enabled: false
tserver_stderrthreshold: 1
