# very much subject to change, these vars are
# loaded last in testing tooling to be used
# for experimentation while developing this release
---
enable_ysql: true
master_instances: 3
master_stderrthreshold: 0
syslog_address: q-s0.docker.services-network.splunk.bosh
syslog_port: 5514
syslog_tls_enabled: false
tserver_instances: 3
tserver_stderrthreshold: 0
