name: yugabyte
blobstore:
  provider: s3
  options:
    # using a weird uuidgen snippet here as a prefix because we don't want to
    # hijack any global s3 bucket naming like "yugabyte-boshrelease" quite yet
    bucket_name: 8f5378ca-yugabyte-boshrelease
