---
- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/callhome_enabled?
  value: ((callhome_enabled))

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/callhome_enabled?
  value: ((callhome_enabled))
