---
- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/stop_logging_if_full_disk?
  value: ((master_stop_logging_if_full_disk))

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/stop_logging_if_full_disk?
  value: ((tserver_stop_logging_if_full_disk))
