---
processes:
  - name: yb-tserver
    executable: /var/vcap/packages/yugabyte/bin/yb-tserver
    persistent_disk: true
    args:
      - --bytes_durable_wal_write_mb=<%= p("bytes_durable_wal_write_mb") %>
      - --callhome_collection_level=<%= p("callhome_collection_level") %>
      - --callhome_enabled=<%= p("callhome_enabled") %>
      - --callhome_interval_secs=<%= p("callhome_interval_secs") %>
      - --callhome_url=<%= p("callhome_url") %>
      - --cql_proxy_bind_address=<%= spec.address %>:<%= p("cql_proxy_bind_port") %>
      - --cql_table_is_transactional_by_default=<%= p("cql_table_is_transactional_by_default") %>
      - --default_memory_limit_to_ram_ratio=<%= p("default_memory_limit_to_ram_ratio") %>
      - --durable_wal_write=<%= p("durable_wal_write") %>
      - --enable_ysql=<%= p("enable_ysql") %>
      - --flagfile=/var/vcap/jobs/yb-tserver/config/tserver.conf
      - --fs_data_dirs=/var/vcap/store/yb-tserver
      - --interval_durable_wal_write_ms=<%= p("interval_durable_wal_write_ms") %>
      - --log_dir=/var/vcap/sys/log/yb-tserver
      - --logtostderr=<%= p("logtostderr") %>
      - --max_log_size=<%= p("max_log_size") %>
      - --minloglevel=<%= p("minloglevel") %>
      - --pgsql_proxy_bind_address=<%= spec.address %>:<%= p("pgsql_proxy_bind_port") %>
      - --placement_cloud=<%= p("placement_cloud") %>
      - --placement_region=<%= p("placement_region") %>
      - --placement_zone=<%= p("placement_zone", spec.az) %>
      - --redis_proxy_bind_address=<%= spec.address %>:<%= p("redis_proxy_bind_port") %>
      - --rpc_bind_addresses=<%= spec.address %>:<%= p("rpc_bind_addresses_port") %>
      - --server_broadcast_addresses=<%= spec.address %>:<%= p("rpc_bind_addresses_port") %>
      - --server_dump_info_path=/var/vcap/sys/log/yb-tserver/tserver-info
      - --stderrthreshold=<%= p("stderrthreshold") %>
      - --stop_logging_if_full_disk=<%= p("stop_logging_if_full_disk") %>
      - --stop_on_parent_termination=<%= p("stop_on_parent_termination") %>
      - --tserver_master_addrs=<%= m = link("yb-master"); m.instances.map { |i| "#{i.address}:#{m.p('rpc_bind_addresses_port')}" }.join(",") %>
      - --use_cassandra_authentication=true
      - --v=<%= p("v") %>
      - --webserver_interface=<%= spec.address %>
      - --webserver_port=<%= p("webserver_port") %>
      - --yb_num_shards_per_tserver=<%= p("yb_num_shards_per_tserver") %>
      - --ysql_default_transaction_isolation='<%= p("ysql_default_transaction_isolation") %>'
      - --ysql_hba_conf=<%= p("ysql_hba_conf") %>
      - --ysql_log_min_messages=<%= p("ysql_log_min_messages") %>
      - --ysql_log_statement='<%= p("ysql_log_statement") %>'
      - --ysql_max_connections=<%= p("ysql_max_connections") %>
      - --ysql_num_shards_per_tserver=<%= p("ysql_num_shards_per_tserver") %>

    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    env:
      ENABLE_MANUAL_YSQL_INIT: <%= p("enable_ysql") %>
    hooks:
      pre_start: /var/vcap/jobs/yb-tserver/bin/pre_start
