---
processes:
  - name: yb-tserver
    workdir: /var/vcap/data/packages/yugabyte/2a0089f71899ee62de9d4b69e69af783745c0881
    executable: bin/yb-tserver
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-tserver/config/tserver.conf
    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
    unsafe:
      privileged: true
