---
processes:
  - name: yb-tserver
    executable: /var/vcap/packages/yugabyte/bin/yb-tserver
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-tserver/config/tserver.conf
    env:
      PATH: "${PATH}:/var/vcap/packages/yugabyte/postgres/bin"
      YB_HOME: /var/vcap/packages/yugabyte
