---
processes:
  - name: yb-tserver
    executable: /var/vcap/packages/yugabyte/bin/yb-tserver
    persistent_disk: true
    args:
      - --flagfile=/var/vcap/jobs/yb-tserver/config/tserver.conf
    limits:
      open_files: <%= p("bpm.limits.open_files") %>
      processes: <%= p("bpm.limits.processes") %>
