---
- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/tls?/allow_insecure_connections?
  value: ((tserver_allow_insecure_connections))

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/tls?/use_client_to_server_encryption?
  value: ((use_client_to_server_encryption))
