---
- type: replace
  path: /variables?/-
  value:
    name: yugabyte-server-tls-master
    type: certificate
    update_mode: ((yugabyte_server_tls_update_mode))
    options:
      ca: /services/tls_ca
      common_name: ((yugabyte_server_tls_common_name))
    consumes:
      alternative_name:
        from: yb-master-address-link
        properties: { wildcard: true }

- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/tls?
  value:
    allow_insecure_connections: ((master_allow_insecure_connections))
    use_node_to_node_encryption: ((use_node_to_node_encryption))
    node:
      ca: ((yugabyte-server-tls-master.ca))
      cert: ((yugabyte-server-tls-master.certificate))
      key: ((yugabyte-server-tls-master.private_key))

# update yb-admin to support connecting to the cluster using TLS
# one day this should be configured through consuming bosh links properties
# rather than statically configured
- type: replace
  path: /instance_groups/name=setup_redis_table/jobs/name=yb-admin/properties?/tls?
  value:
    enabled: true
    node:
      ca: ((yugabyte-server-tls-master.ca))

######################################################

- type: replace
  path: /variables?/-
  value:
    name: yugabyte-server-tls-tserver
    type: certificate
    update_mode: ((yugabyte_server_tls_update_mode))
    options:
      ca: /services/tls_ca
      common_name: ((yugabyte_server_tls_common_name))
    consumes:
      alternative_name:
        from: yb-tserver-address-link
        properties: { wildcard: true }

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/tls?
  value:
    use_node_to_node_encryption: ((use_node_to_node_encryption))
    node:
      ca: ((yugabyte-server-tls-tserver.ca))
      cert: ((yugabyte-server-tls-tserver.certificate))
      key: ((yugabyte-server-tls-tserver.private_key))
