---
- type: replace
  path: /variables?/-
  value:
    name: yugabyte-server-master-tls
    type: certificate
    update_mode: ((yugabyte_server_tls_update_mode))
    options:
      ca: /services/tls_ca
      common_name: yugabyte-boshrelease
      alternative_names: []
      extended_key_usage:
        - client_auth
        - server_auth
    consumes:
      alternative_name:
        from: yb-master-address-link
        properties: { wildcard: true }

- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/tls?
  value:
    allow_insecure_connections: ((master_allow_insecure_connections))
    use_node_to_node_encryption: ((use_node_to_node_encryption))
    node:
      ca: ((yugabyte-server-master-tls.ca))
      cert: ((yugabyte-server-master-tls.certificate))
      key: ((yugabyte-server-master-tls.private_key))

######################################################

- type: replace
  path: /variables?/-
  value:
    name: yugabyte-server-tserver-tls
    type: certificate
    update_mode: ((yugabyte_server_tls_update_mode))
    options:
      ca: /services/tls_ca
      common_name: yugabyte-boshrelease
      alternative_names: []
      extended_key_usage:
        - client_auth
        - server_auth
    consumes:
      alternative_name:
        from: yb-tserver-address-link
        properties: { wildcard: true }

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/tls?
  value:
    use_node_to_node_encryption: ((use_node_to_node_encryption))
    node:
      ca: ((yugabyte-server-tserver-tls.ca))
      cert: ((yugabyte-server-tserver-tls.certificate))
      key: ((yugabyte-server-tserver-tls.private_key))
