# WARNING
#
# WORK IN PROGRESS
#
---
- type: replace
  path: /variables?/-
  value:
    name: yugabyte_server_tls
    type: certificate
    update_mode: ((yugabyte_server_tls_update_mode))
    options:
      ca: /services/tls_ca
      common_name: yugabyte-boshrelease
      # TODO this needs to be configured with bosh-links for best experience
      alternative_names:
        - "*.tserver.((network)).((deployment_name)).bosh"
      extended_key_usage:
        - client_auth
        - server_auth
    consumes:
      alternative_name:
        from: yb-master-address-link
        properties: { wildcard: true }

- type: replace
  path: /instance_groups/name=master/jobs/name=yb-master/properties?/tls?
  value:
    allow_insecure_connections: ((master_allow_insecure_connections))
    use_node_to_node_encryption: ((use_node_to_node_encryption))
    node:
      ca: ((yugabyte_server_tls.ca))
      cert: ((yugabyte_server_tls.certificate))
      key: ((yugabyte_server_tls.private_key))

- type: replace
  path: /instance_groups/name=tserver/jobs/name=yb-tserver/properties?/tls?
  value:
    use_node_to_node_encryption: ((use_node_to_node_encryption))
    node:
      ca: ((yugabyte_server_tls.ca))
      cert: ((yugabyte_server_tls.certificate))
      key: ((yugabyte_server_tls.private_key))
