---
- type: replace
  path: /instance_groups/name=master/jobs/-
  value:
    name: yb-tserver
    release: yugabyte
    consumes: { yb-master: { from: yb-master-provider } }
    provides: { yb-tserver: { as: yb-tserver-provider } }
    properties:
      gflags: ((tserver_gflags))
