---
name: "configure-repo-labels"

on:
  push:
    paths:
      - .github/**/*
  schedule:
    - cron: '0 */12 * * *'
  repository_dispatch:
    types: [configure-labels-event]


jobs:
  configure-repo-labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: run-labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v1
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
